services:
  - type: web
    name: amo-telegram-notify
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
